---
title: "RDO_Trucking"
output: html_document
date: "2025-11-21"
---

## R Markdown

# rdo_trucking_ompr.R
# Install packages if needed:
# install.packages(c("ompr","ompr.roi","ROI.plugin.glpk","magrittr","dplyr","tidyr"))
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(root.dir = 'RDO_Trucking') #This sets the working
library(readr, quietly = TRUE) # We import this library so that we can read in things from csv files.
library(ompr)
library(ompr.roi)
library(ROI.plugin.glpk)
library(magrittr)
library(dplyr)
library(tidyr)
library(tibble)
```

```{r}
getwd()
list.files()
```
#Sets
```{r}
drivers_csv <- read_csv("Drivers.csv")
drivers_id <- drivers_csv$DriverID
drivers_maxnight <- drivers_csv$MaxNightsOvernightPerWeek
num_drivers <- length(drivers_id)
names(drivers_maxnight) <- drivers_id
max_load <- drivers_csv$`Max Load Pounds`
names(max_load) <- drivers_id
drivers_location <- setNames(
    paste(drivers_csv$Location, drivers_csv$State, sep = ", "),
    drivers_csv$DriverID
)

drivers_id
drivers_maxnight
max_load
drivers_location
```

```{r}
locations_csv <- read_csv("Locations.csv")
locations <- paste(locations_csv$City, locations_csv$State, sep = ", ")
locations
```

```{r}
mileage_csv <- read_csv("MileageMatrix.csv")
locations <- mileage_csv$Origination
mileage <- as.matrix(mileage_csv[,-1]) # everything except the first column
rownames(mileage) <- locations

mileage
```

```{r}
workorders_csv <- read_csv("TruckingWorkorders.csv")
workorders_id <- workorders_csv$WorkOrderNumber

# Origin
w_order_start <- setNames(workorders_csv$Origination, workorders_id)
# Destination
w_order_end <- setNames(workorders_csv$Destination, workorders_id)

# Weight
w_order_weight <- setNames(workorders_csv$LoadWeight, workorders_id)

# Days due
w_order_due <- setNames(workorders_csv$DeliveryDays, workorders_id)

start


```


